name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          global-json-file: global.json

      - name: Run dotnet build ForEditing
        run: |
          dotnet build ForEditing.fsproj 

      - name: Run combineIntoOneFile.fsx
        # Run it once before building all target frameworks in parallel below.
        # The parallel builds run it again, but then find the combined file unchanged and don't race writing to it.
        run: |
          dotnet fsi combineIntoOneFile.fsx

      - name: Run dotnet build ForPublishing
        run: |
          dotnet build ForPublishing.fsproj -c Release

